version: '3.8'

services:
  ddddocr-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - API_TOKEN=your_secure_token_here
      - DEBUG=1
    restart: always
